/*
 * Sample REST Application
 * The Application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.HelloModel;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HelloApi
 */
public class HelloApiTest {

    private final HelloApi api = new HelloApi();

    
    /**
     * helloRequest
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void helloRequestTest() throws ApiException {
        String name = null;
        HelloModel body = null;
        // HelloModel response = api.helloRequest(name, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayHelloTest() throws ApiException {
        String name = null;
        String firstName = null;
        // String response = api.sayHello(name, firstName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayHelloWithModelTest() throws ApiException {
        String name = null;
        String firstName = null;
        // HelloModel response = api.sayHelloWithModel(name, firstName);

        // TODO: test validations
    }
    
    /**
     * uploads an image
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadFileTest() throws ApiException {
        String name = null;
        File file = null;
        // String response = api.uploadFile(name, file);

        // TODO: test validations
    }
    
}
