/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.api;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.core.MediaType;

import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.WebClient;
import org.apache.cxf.jaxrs.ext.multipart.Attachment;
import org.apache.cxf.jaxrs.provider.MultipartProvider;
import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import io.swagger.model.ModelApiResponse;
import io.swagger.model.Pet;




/**
 * API tests for PetApi
 */
public class PetApiRemoteTest {


    private PetApi api;

    private org.apache.cxf.jaxrs.client.Client client;
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        providers.add(new MultipartProvider());
        
        api = JAXRSClientFactory.create("http://localhost:8080/services", PetApi.class, providers);
        client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client);
        client.encoding("UTF-8");
        client.type(MediaType.MULTIPART_FORM_DATA);
    }

    @Test
    public void uploadFileTest() throws FileNotFoundException {

        Long petId = new Long(1);
        InputStream mybytesInput = new FileInputStream("c:/temp/test.txt");
    
        org.apache.cxf.jaxrs.ext.multipart.ContentDisposition cd = new org.apache.cxf.jaxrs.ext.multipart.ContentDisposition(
                "attachment;filename=datei.txt");
        Attachment attachment = new Attachment("file", mybytesInput, cd);

        String request = "testxxx";
        // Attachment attRequest = new Attachment("additionalMetadata",
        // MediaType.APPLICATION_JSON_TYPE.toString(),
        // (Object) request);

        ModelApiResponse response = api.uploadFile(petId, request, attachment);


        //assertNotNull(response);
        // TODO: test validations
    }
    
}
