/**
 * Sample REST Application
 * The Application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HelloModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HelloModel'));
  } else {
    // Browser globals (root is window)
    if (!root.SampleRestApplication) {
      root.SampleRestApplication = {};
    }
    root.SampleRestApplication.HelloApi = factory(root.SampleRestApplication.ApiClient, root.SampleRestApplication.HelloModel);
  }
}(this, function(ApiClient, HelloModel) {
  'use strict';

  /**
   * Hello service.
   * @module api/HelloApi
   * @version 1.0.0
   */

  /**
   * Constructs a new HelloApi. 
   * @alias module:api/HelloApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the sayHello operation.
     * @callback module:api/HelloApi~sayHelloCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {String} name 
     * @param {String} firstName 
     * @param {module:api/HelloApi~sayHelloCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.sayHello = function(name, firstName, callback) {
      var postBody = null;

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw new Error("Missing the required parameter 'name' when calling sayHello");
      }

      // verify the required parameter 'firstName' is set
      if (firstName == undefined || firstName == null) {
        throw new Error("Missing the required parameter 'firstName' when calling sayHello");
      }


      var pathParams = {
      };
      var queryParams = {
        'name': name,
        'firstName': firstName
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/hello', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the sayHelloWithModel operation.
     * @callback module:api/HelloApi~sayHelloWithModelCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelloModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {String} name 
     * @param {module:api/HelloApi~sayHelloWithModelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelloModel}
     */
    this.sayHelloWithModel = function(name, callback) {
      var postBody = null;

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw new Error("Missing the required parameter 'name' when calling sayHelloWithModel");
      }


      var pathParams = {
      };
      var queryParams = {
        'name': name
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = HelloModel;

      return this.apiClient.callApi(
        '/helloGreeting', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
